### ISSUE TITLE
Inconsistent memory display

### ISSUE THREAD

**Issue by yh36** [discovery-unicamp/ale-exercise-book#2]
When using `disass` command to dump memory content, each row normally displays two bytes. But I saw this exception which displays four bytes. Is this a known issue? As each row only dumps two bytes, can we just display four hex digits instead of eight digits, which is hard to read?
![image](https://github.com/user-attachments/assets/bd562927-331e-4c7c-a572-14fcbfd87b99)

There is another typo on Chapter 6 and Chapter 6.1.
1.  What does `&` mean here?
![image](https://github.com/user-attachments/assets/c3f7de2c-5a1e-4d7a-afb8-5671533dce25)
2.  Do you mean **exercise 3.1**
![image](https://github.com/user-attachments/assets/016eba34-d100-4817-bd9b-3d31abba7a19)

**Comment by SerodioJ** [comment]
Hi Yi Hou,

Thanks for pointing out these typos. The first should be `7` instead of `&`. I will be fixing them in the next version of the book.

Regarding the `disass` command, we weren't aware of this issue. In this case the simulator is a WebAssembly artifact, that has been compiled from the [VeeR-ISS](https://github.com/chipsalliance/VeeR-ISS) simulator, so I believe it might be an issue with the original simulator.  The same thing is valid for the way the hex values are being displayed.

**Comment by SerodioJ** [comment]
The `disass` command issue is related to the VeeR-ISS simulator, and the typos have been fixed, so I will close this issue.
